### ISSUE TITLE
Possible documentation update: EXPO_USE_METRO_WORKSPACE_ROOT=1 to build

### ISSUE THREAD

**Issue by tbloomfi** [animo/paradym-wallet#109]
I was getting a 404 error for the expo-router and was only able to run the app after exporting EXPO_USE_METRO_WORKSPACE_ROOT=1 as per the monorepo instructions. 

Should this be added to the build instructions or added automatically in the package.json file?

**Comment by TimoGlastra** [comment]
Hmm I've been able to build it fine without that command. What command are you adding this to? And from which directory are you running the app?

**Comment by timbl-ont** [comment]
Just tested again with a fresh clone of the main branch with the same result - via Android simulator. 

Node Version: v18.20.2

I followed the Readme:

```
yarn
cd apps/expo
yarn prebuild
yarn android
```

Screen shot:
<img width="416" alt="Screenshot 2024-06-04 at 11 42 31 AM" src="https://github.com/animo/paradym-wallet/assets/163455524/e17ce42d-3805-430f-a663-2467b4665f86">

The same steps after running "export EXPO_USE_METRO_WORKSPACE_ROOT=1" in the shell fixed the error, launching the wallet. This setting is from here: "https://docs.expo.dev/guides/monorepos" - the note on Expo Router.

**Comment by TimoGlastra** [comment]
Okay thanks for looking into it! @berendsliedrecht something you can add with the restructure soon?

**Comment by berendsliedrecht** [comment]
Yes, I'll pay attention to it!

**Comment by TimoGlastra** [comment]
I ran into the same issue -- have fixed it locally and will open a PR. Thanks for reporting @timbl-ont
